AUGMENT:
  BRIGHTNESS: 0.0
  CONTRAST: 0.0
  CROP_MIN_IOUS:
  - 0.1
  - 0.3
  - 0.5
  - 0.7
  - 0.9
  CROP_MIN_SIZE: 0.3
  CROP_PROB: 0.5
  FLIP_PROB_TRAIN: 0.5
  HUE: 0.0
  MULT_MIN_SIZE_TRAIN:
  - 480
  - 560
  - 640
  - 720
  - 800
  SATURATION: 0.0
  USE_RA: 0
  VERTICAL_FLIP_PROB_TRAIN: 0.0
DATALOADER:
  ASPECT_RATIO_GROUPING: false
  DISTRIBUTE_CHUNK_AMONG_NODE: false
  MIN_KPS_PER_IMS: 0
  NUM_WORKERS: 0
  SIZE_DIVISIBILITY: 32
  USE_RANDOM_SEED: false
DATASETS:
  ADD_DET_PROMPT: false
  ADD_DET_PROMPT_ADVANCED: false
  ADD_NORMED_CXCY: false
  ALTERNATIVE_TRAINING: false
  BING_INDEX_LIST: []
  BOX_THRESHOLD: 0.1
  CAPTION_CONF: 0.5
  CAPTION_FORMAT_VERSION: v2
  CAPTION_MIN_BOX: 1
  CAPTION_NMS: -1.0
  CAPTION_PROMPT: null
  CLASS_AGNOSTIC: false
  CLASS_CONCAT: false
  COCO_COPY: 1
  CONTROL_PROB:
  - 0.0
  - 0.0
  - 0.5
  - 0.0
  DETECT_NONEXIST: false
  DISABLE_CLIP_TO_IMAGE: false
  DISABLE_SHUFFLE: false
  DIVER_BOX_FOR_VQA: false
  EXCLUDE_CROWD: true
  FEW_SHOT: 5
  FLICKR_COPY: 8
  FLICKR_GT_TYPE: separate
  FULL_QUESTION_PROB: 0.5
  FURTHER_SCREEN: true
  GENERAL_COPY: -1
  GENERAL_COPY_TEST: -1
  INFERENCE_CAPTION: false
  IN_COPY: 2
  LOCAL_DEBUG: false
  LVIS_COPY: 1
  LVIS_USE_NORMAL_AP: false
  MAX_BOX: -1
  MIXED_COPY: 4
  MULTISTAGE_TRAINING: false
  NEG_QUESTION_PROB: 0.8
  NO_MINUS_ONE_FOR_ONE_HOT: false
  NO_RANDOM_PACK_PROBABILITY: 0.4
  OBJECT365_COPY: 2
  OI_COPY: 1
  ONE_HOT: false
  OVERRIDE_CATEGORY: null
  PACK_RANDOM_CAPTION_NUMBER: 20
  POS_QUESTION_PROB: 0.6
  PREDEFINED_TEXT: null
  PROMPT_LIMIT_NEG: -1
  PROMPT_VERSION: ''
  RANDOM_PACK_PROB: 0.5
  RANDOM_SAMPLE_NEG: 85
  REGISTER:
    lvis_evaluation_mini_val:
      ann_file: coco/annotations/lvis_v1_minival_inserted_image_name.json
      img_dir: coco
    lvis_evaluation_val:
      ann_file: coco/annotations/lvis_od_val.json
      img_dir: coco
  REPLACE_CLEAN_LABEL: false
  SAFEGUARD_POSITIVE_CAPTION: true
  SAMPLE_NEGATIVE_FOR_GROUNDING_DATA: -1.0
  SAMPLE_RATIO: 0.0
  SEPARATION_TOKENS: '. '
  SEP_AT_LAST: false
  SHUFFLE_SEED: 0
  SPECIAL_SAFEGUARD_FOR_COCO_GROUNDING: true
  SUPRESS_QUERY: null
  TEST:
  - lvis_evaluation_mini_val
  TEST_DATASETNAME_SUFFIX: ''
  TRAIN:
  - lvis_grounding_train_for_obj365
  TRAIN_DATASETNAME_SUFFIX: ''
  USE_CAPTION_PROMPT: false
  USE_COCO_FORMAT: false
  USE_CROWD: false
  USE_OD_AUG: false
  USE_OVERRIDE_CATEGORY: true
  USE_SUPRESS_QUERY: false
  VG_COPY: 3
GLIPKNOW:
  GPT3_NUM: 5
  KNOWLEDGE_FILE: ''
  KNOWLEDGE_TYPE: ''
  LAN_FEATURE_AGG_TYPE: first
  MAX_NUM_CLASSES_PER_BATCH_TRAIN: -1
  PARALLEL_LANGUAGE_INPUT: false
  WIKI_AND_GPT3: false
GROUNDINGDINO:
  backbone: swin_T_224_1k
  backbone_freeze_keywords: null
  box_threshold: 0.05
  dec_layers: 6
  dec_n_points: 4
  dec_pred_bbox_embed_share: true
  dim_feedforward: 2048
  dn_bbox_coef: 1.0
  dn_box_noise_scale: 1.0
  dn_label_coef: 1.0
  dn_label_noise_ratio: 0.5
  dn_labelbook_size: 2000
  dropout: 0.0
  embed_init_tgt: true
  enabled: false
  enc_layers: 6
  enc_n_points: 4
  focal_alpha: 0.25
  fusion_dropout: 0.0
  fusion_droppath: 0.1
  hidden_dim: 256
  loss_bbox_coef: 5.0
  loss_ce_coef: 2.0
  loss_giou_coef: 2.0
  matcher:
    focal_alpha: 0.25
    matcher_type: HungarianMatcher
    set_cost_bbox: 5.0
    set_cost_class: 1.0
    set_cost_giou: 2.0
  max_text_len: 256
  modelname: groundingdino
  nheads: 8
  num_feature_levels: 4
  num_patterns: 0
  num_queries: 900
  pe_temperatureH: 20
  pe_temperatureW: 20
  position_embedding: sine
  pre_norm: false
  query_dim: 4
  return_interm_indices:
  - 1
  - 2
  - 3
  sub_sentence_present: true
  text_dropout: 0.0
  text_encoder_type: bert-base-uncased
  transformer_activation: relu
  two_stage_bbox_embed_share: false
  two_stage_class_embed_share: false
  two_stage_type: standard
  use_checkpoint: true
  use_fusion_layer: true
  use_text_cross_attention: true
  use_text_enhancer: true
  use_transformer_ckpt: true
INPUT:
  FIX_RES: false
  FORMAT: ''
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: 800
  PIXEL_MEAN:
  - 103.53
  - 116.28
  - 123.675
  PIXEL_STD:
  - 57.375
  - 57.12
  - 58.395
  TO_BGR255: true
MODEL:
  ADAPTER: false
  ATSS:
    CHANNELS: 128
    DETECTIONS_PER_IMG: 300
    INFERENCE_TH: 0.05
    INFERENCE_TH_TRAIN: 0.0
    NMS_TH: 0.6
    NUM_CLASSES: 8
    NUM_CONVS: 4
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N: 1000
    PRE_NMS_TOP_N_TRAIN: 3000
    PRIOR_PROB: 0.01
    REG_LOSS_WEIGHT: 2.0
    TOPK: 9
    USE_BN: false
    USE_DFCONV: false
    USE_DYRELU: false
    USE_GN: false
    USE_SE: false
  BACKBONE:
    CONV_BODY: SWINT-FPN-RETINANET
    EFFICIENT_DET_BIFPN_VERSION: 0
    EFFICIENT_DET_COMPOUND: 0
    EFFICIENT_DET_START_FROM: 3
    FPN_LAYER: []
    FREEZE: true
    FREEZE_CONV_BODY_AT: -1
    GROUP: 1
    LAYER_SEARCH: {}
    LAYER_SETUP:
    - 3
    - 4
    - 6
    - 3
    NORM_LEVEL: 3
    OUT_CHANNELS: 256
    OUT_FEATURES:
    - stage2
    - stage3
    - stage4
    - stage5
    RESET_BN: false
    USE_BN: false
    USE_CHECKPOINT: false
    USE_DFCONV: false
    USE_DYRELU: false
    USE_EN: false
    USE_GN: false
    USE_NSYNCBN: false
    USE_SE: false
    USE_SYNCBN: false
  BIFPN:
    NUM_REPEATS: 1
    USE_ATTENTION: true
  BOX_ON: true
  CACHE_ADAPTER: false
  CACHE_PATH: ''
  CLIP:
    CONTEXT_LENGTH: 256
    DROP_PATH: 0.0
    HEADS: 8
    LAYERS: 12
    TOKENIZER: clip
    VOCAB_SIZE: 49408
    WIDTH: 512
  DEBUG: false
  DEVICE: cuda
  DYHEAD:
    ADAPTER:
      RATIO: 0.2
    CHANNELS: 256
    CONV_FUNC: ''
    COSINE_SCALE: -1.0
    FUSE_CONFIG:
      ADD_LINEAR_LAYER: false
      CLAMP_BERTATTN_MAX_FOR_OVERFLOW: true
      CLAMP_BERTATTN_MIN_FOR_UNDERFLOW: true
      CLAMP_DOT_PRODUCT: true
      CLAMP_MAX_FOR_OVERFLOW: true
      CLAMP_MIN_FOR_UNDERFLOW: true
      CONDITIONAL_GATE: true
      CONTRASTIVE_ALIGN_LOSS_WEIGHT: 1.0
      CONTRASTIVE_HIDDEN_DIM: 64
      DOT_PRODUCT_TOKEN_LOSS_WEIGHT: 1.0
      DO_LANG_PROJ_OUTSIDE_CHECKPOINT: false
      EARLY_FUSE_ON: true
      JOINT_EMB_DROPOUT: 0.1
      JOINT_EMB_SIZE: 256
      JOINT_MLP_LAYERS: 2
      JOINT_OUT_SIZE: 256
      MLM_LOSS: false
      MLM_LOSS_COEF: 1.0
      MLM_LOSS_FOR_ONLY_POSITIVES: true
      MLM_OBJ_FOR_ONLY_POSITIVE: false
      NO_MASK_FOR_GOLD: false
      NO_MASK_FOR_OD: false
      SEPARATE_BIDIRECTIONAL: false
      SHALLOW_CONTRASTIVE_HIDDEN_DIM: 64
      SHALLOW_CONTRASTIVE_LOSS_WEIGHT: 1.0
      SHALLOW_MAX_POSITIVE_ANCHORS: 100
      STABLE_SOFTMAX_2D: false
      TOKEN_ALPHA: 0.25
      TOKEN_GAMMA: 2.0
      TOKEN_LOSS_WEIGHT: 1.0
      TYPE: MHA-B
      USE_BACKBONE_SHALLOW_CONTRASTIVE_LOSS: false
      USE_CLASSIFICATION_LOSS: false
      USE_CONTRASTIVE_ALIGN_LOSS: false
      USE_DOT_PRODUCT_TOKEN_LOSS: true
      USE_FUSED_FEATURES_DOT_PRODUCT: true
      USE_LAYER_SCALE: true
      USE_SHALLOW_CONTRASTIVE_LOSS: false
      USE_SHALLOW_ZERO_PADS: false
      USE_TOKEN_LOSS: false
    GROUPS: 1
    LOG_SCALE: 0.0
    NUM_CLASSES: 1204
    NUM_CONVS: 8
    PRIOR_PROB: 0.01
    SCORE_AGG: MEAN
    SHALLOW_LOG_SCALE: 0.0
    TOPK: 9
    USE_CHECKPOINT: false
    USE_DFCONV: true
    USE_DYFUSE: true
    USE_DYRELU: true
    USE_GN: true
    USE_NSYNCBN: false
    USE_SYNCBN: false
  EVO_NORM:
    EPSILON: 1.0e-05
    NUM_GROUPS: 8
  FCOS:
    CENTERNESS_ON_REG: false
    CENTER_SAMPLING_RADIUS: 0.0
    DETECTIONS_PER_IMG: 300
    FPN_STRIDES:
    - 8
    - 16
    - 32
    - 64
    - 128
    INFERENCE_TH: 0.05
    INFERENCE_TH_TRAIN: 0.0
    IOU_LOSS_TYPE: iou
    NMS_TH: 0.6
    NORM_REG_TARGETS: false
    NUM_CLASSES: 8
    NUM_CONVS: 4
    POST_NMS_TOP_N_TRAIN: 1000
    PRE_NMS_TOP_N: 1000
    PRE_NMS_TOP_N_TRAIN: 3000
    PRIOR_PROB: 0.01
    USE_BN: false
    USE_DFCONV: false
    USE_GN: false
    USE_GT_CENTER: false
  FOCAL:
    BBOX_REG_BETA: 0.11
    BBOX_REG_WEIGHT: 4.0
    BG_IOU_THRESHOLD: 0.4
    FG_IOU_THRESHOLD: 0.5
    LOSS_ALPHA: 0.25
    LOSS_GAMMA: 2.0
  FPN:
    DROP_BLOCK: true
    DROP_PROB: 0.3
    DROP_SIZE: 3
    FREEZE: true
    RETURN_SWINT_FEATURE_BEFORE_FUSION: false
    USE_DYHEAD: false
    USE_DYRELU: false
    USE_GN: false
    USE_PAN: false
    USE_RELU: false
    USE_SPP: false
  FREEZE_CLASSIFIER: false
  GROUP_NORM:
    DIM_PER_GP: -1
    EPSILON: 1.0e-05
    NUM_GROUPS: 16
  KEYPOINT_ON: false
  LANGUAGE_BACKBONE:
    BIDIRECTIONAL: true
    CORPUS_PATH: ''
    DROPOUT_P: 0.2
    FREEZE: false
    HIDDEN_SIZE: 512
    INPUT_DROPOUT_P: 0.5
    LANG_DIM: 768
    MASK_SPECIAL: false
    MAX_QUERY_LEN: 256
    MODEL_TYPE: bert-base-uncased
    N_LAYERS: 1
    PAD_MAX: true
    RNN_TYPE: lstm
    TOKENIZER_TYPE: bert-base-uncased
    UNUSED_TOKEN: 106
    USE_CHECKPOINT: false
    VARIABLE_LENGTH: true
    VOCAB_SIZE: 0
    WEIGHT: ''
    WORD_EMBEDDING_SIZE: 512
    WORD_VEC_SIZE: 512
  LINEAR_PROB: false
  MASK_ON: false
  META_ARCHITECTURE: GeneralizedVLRCNN_New
  MULTITASK: {}
  ONNX: false
  PRETRAIN_NAME: ''
  RESNETS:
    BACKBONE_OUT_CHANNELS: 1024
    DEFORMABLE_GROUPS: 1
    NUM_GROUPS: 1
    RES2_OUT_CHANNELS: 256
    RES5_DILATION: 1
    REVISION: resnet_light
    STAGE_WITH_DCN:
    - false
    - false
    - false
    - false
    STEM_FUNC: StemWithFixedBatchNorm
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: true
    TRANS_FUNC: BottleneckWithFixedBatchNorm
    USE_AVG_DOWN: false
    USE_STEM3X3: false
    WIDTH_PER_GROUP: 64
    WITH_MODULATED_DCN: false
    WITH_SE: false
  RETINANET:
    DETECTIONS_PER_IMG: 300
    INFERENCE_TH: 0.05
    NMS_TH: 0.4
    NUM_CLASSES: 81
    NUM_CONVS: 4
    PRE_NMS_TOP_N: 1000
    PRIOR_PROB: 0.01
  ROI_BOX_HEAD:
    CONV_HEAD_DIM: 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 8
    NUM_STACKED_CONVS: 4
    POOLER_ALIGNED: false
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES:
    - 0.125
    - 0.0625
    - 0.03125
    - 0.015625
    - 0.0078125
    PREDICTOR: FastRCNNPredictor
    USE_GN: false
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512
    BBOX_REG_WEIGHTS:
    - 10.0
    - 10.0
    - 5.0
    - 5.0
    BG_IOU_THRESHOLD: 0.5
    DETECTIONS_PER_IMG: 300
    FG_IOU_THRESHOLD: 0.5
    NMS: 0.5
    POSITIVE_FRACTION: 0.25
    SCORE_THRESH: 0.05
    USE_FPN: false
  ROI_KEYPOINT_HEAD:
    CONV_LAYERS:
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    - 512
    FEATURE_EXTRACTOR: KeypointRCNNFeatureExtractor
    KEYPOINT_NAME: []
    MLP_HEAD_DIM: 1024
    NUM_CLASSES: 17
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: &id001
    - 0.0625
    PREDICTOR: KeypointRCNNPredictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
  ROI_MASK_HEAD:
    CONV_LAYERS:
    - 256
    - 256
    - 256
    - 256
    DILATION: 1
    FEATURE_EXTRACTOR: ResNet50Conv5ROIFeatureExtractor
    HG_SCALE: 1
    MLP_HEAD_DIM: 1024
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 0
    POOLER_SCALES: *id001
    POSTPROCESS_MASKS: false
    POSTPROCESS_MASKS_THRESHOLD: 0.5
    PREDICTOR: MaskRCNNC4Predictor
    RESOLUTION: 14
    SHARE_BOX_FEATURE_EXTRACTOR: true
    USE_GN: false
  RPN:
    ANCHOR_SHIFT:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    ANCHOR_SIZES:
    - 64
    - 128
    - 256
    - 512
    - 1024
    ANCHOR_STRIDE:
    - 8
    - 16
    - 32
    - 64
    - 128
    ASPECT_RATIOS:
    - 1.0
    BATCH_SIZE_PER_IMAGE: 256
    BG_IOU_THRESHOLD: 0.3
    FG_IOU_THRESHOLD: 0.7
    FORCE_BOXES: false
    FPN_POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 2000
    FREEZE: true
    MIN_SIZE: 0
    NMS_THRESH: 0.7
    OCTAVE: 2.0
    POSITIVE_FRACTION: 0.5
    POST_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 6000
    PRE_NMS_TOP_N_TRAIN: 12000
    RETURN_FUSED_FEATURES: false
    RPN_HEAD: SingleConvRPNHead
    SCALES_PER_OCTAVE: 1
    STRADDLE_THRESH: 0
    USE_FPN: true
    USE_RELATIVE_SIZE: false
  RPN_ARCHITECTURE: VLDYHEAD
  RPN_ONLY: true
  SPEC: {}
  SWINT:
    APE: false
    DEPTHS:
    - 2
    - 2
    - 18
    - 2
    DROP_PATH_RATE: 0.4
    EMBED_DIM: 192
    LAYER_SCALE: 0
    MLP_RATIO: 4
    NUM_HEADS:
    - 6
    - 12
    - 24
    - 48
    OUT_CHANNELS:
    - 192
    - 384
    - 768
    - 1536
    OUT_NORM: true
    VERSION: v1
    WINDOW_SIZE: 12
  WEIGHT: MODEL/glip_large_model.pth
OUTPUT_DIR: OUTPUT_EXTRACT_LVIS_VISUAL_QUERY
PATHS_CATALOG: /opt/hpcaas/.mounts/fs-0df31b178aa4037ac/home/jielei/MQ-Det/maskrcnn_benchmark/config/paths_catalog.py
SEARCH:
  CROSSOVER_NUM: 24
  MAX_EPOCH: 20
  MUTATION_NUM: 24
  MUTATION_PROB: 0.1
  POPULATION_NUM: 64
  SELECT_NUM: 20
SOLVER:
  AUTO_TERMINATE_PATIENCE: -1
  BACKBONE_BODY_LR_FACTOR: 1.0
  BASE_LR: 1.0e-05
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 99999999
  CHECKPOINT_PER_EPOCH: -1.0
  CLIP_GRADIENTS:
    CLIP_TYPE: full_model
    CLIP_VALUE: 1.0
    ENABLED: true
    NORM_TYPE: 2.0
  DATASET_LENGTH: -1
  DISABLE_OUTPUT_DISTRIBUTED: false
  FIND_UNUSED_PARAMETERS: false
  GAMMA: 0.1
  GATE_LR: 0.0001
  GRAD_CLIP: 0.0
  IMS_PER_BATCH: 8
  LANG_LR: 1.0e-05
  MAX_EPOCH: 1
  MAX_ITER: 40000
  MAX_NEG_PER_BATCH: 0.1
  MAX_TO_KEEP: 4
  MIN_LR: 1.0e-06
  MODEL_EMA: 0.0
  MOMENTUM: 0.9
  MULTI_MAX_EPOCH: []
  MULTI_MAX_ITER: []
  OPTIMIZER: ADAMW
  PROMPT_PROBING_LEVEL: -1.0
  QUERY_LR: 1.0e-05
  SEED: 0
  STEPS:
  - 0.67
  - 0.89
  STEP_PATIENCE: 5
  TEST_WITH_INFERENCE: true
  TUNING_HIGHLEVEL_OVERRIDE: vision_query
  USE_AMP: true
  USE_AUTOSTEP: true
  USE_COSINE: false
  USE_EMA_FOR_MONITOR: false
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 20
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0
  WEIGHT_DECAY_NORM_FACTOR: 1.0
  WEIGHT_DECAY_SCHEDULE: true
  WEIGHT_DECAY_SCHEDULE_RATIO: 0.667
TENSORBOARD_EXP: OUTPUT
TEST:
  CHUNKED_EVALUATION: 40
  DURING_TRAINING: false
  EVAL_TASK: detection
  EXPECTED_RESULTS: []
  EXPECTED_RESULTS_SIGMA_TOL: 4
  FLIP: true
  IMS_PER_BATCH: 1
  LVIS_RESULTS_SAVE_PATH: ''
  MAX_SIZE: 2500
  MDETR_STYLE_AGGREGATE_CLASS_NUM: 3000
  NUM_CLASSES: 81
  PRE_NMS_TOP_N: 1000
  RANGES:
  - &id002
    - 96
    - 10000
  - *id002
  - &id003
    - 64
    - 10000
  - *id003
  - *id003
  - &id004
    - 0
    - 10000
  - *id004
  - &id005
    - 0
    - 256
  - *id005
  - &id006
    - 0
    - 192
  - *id006
  - - 0
    - 96
  SCALES:
  - 400
  - 500
  - 600
  - 640
  - 700
  - 900
  - 1000
  - 1100
  - 1200
  - 1300
  - 1400
  - 1800
  SELECT_CLASSES: []
  SPECIAL_NMS: none
  SUBSET: -1
  TEST_VISION: false
  TH: 0.6
  USE_MULTISCALE: false
VISION_QUERY:
  ADD_ADAPT_LAYER: false
  ADD_VISION_LAYER: false
  AUGMENT_IMAGE_WITH_QUERY: false
  CONDITION_GATE: true
  CUSTOM_CAT_IDS: null
  CUSTOM_DATA_IDS: null
  DATASET_NAME: ''
  DEBUG: false
  DISABLE_SELECTOR: false
  ENABLED: true
  EXPAND_RATIO: 1.5
  FIX_ATTN_GATE: -1.0
  GATE_REGULARIZATION: false
  GATE_REGULARIZATION_SCALE: 0.1
  LEARNABLE_BANK: false
  MASK_DURING_INFERENCE: false
  MAX_QUERY_NUMBER: 5
  MAX_TEST_QUERY_NUMBER: 100
  NEW_MASK_TOKEN: false
  NONLINEAR_GATE: true
  NO_CAT: true
  NUM_QUERY_PER_CLASS: 5
  NUM_TURNS: 1
  OFFLINE_WITH_ONLINE: false
  OWLVIT: false
  PURE_TEXT_RATE: 0.0
  QUERY_ADDITION_NAME: _L
  QUERY_BANK_PATH: ''
  QUERY_BANK_SAVE_PATH: MODEL/lvis_query_5_pool7_sel_large.pth
  QUERY_FUSION: false
  RANDOM_KSHOT: false
  RETURN_ATTN_GATE_VALUE: false
  SCORE_THRESHOLD: 0.6
  SELECT_FPN_LEVEL: true
  SHARE_KV: false
  SIMILARITY_THRESHOLD: 0.85
  TEXT_DROPOUT: 0.0
  VISION_SCALE: 1.0
local_rank: 0
num_gpus: 1
